### ISSUE TITLE
Great idea, and a few questions about NSP

### ISSUE THREAD

**Issue by HallofFamer** [Yahweasel/nodejs-server-pages#1]
Hello there, I stumbled upon this package and it looks fantastic. I hope you keep up this excellent work. And a few questions:

1. Does this package require shell access/root privilege? Or is it possible to run it just on any shared host that has node/NPM installed? I wish to have it replace the PHP fast-cgi on my apache server, so I am curious about it. 
2. Is it possible to use a backend framework like express and nest.js for the application layer, while keeping NSP as view/presentation files? 
3. The package looks new, how long have you been working on it, and do you plan to continue developing it in the recent and remote future? 

Regards

**Comment by Yahweasel** [comment]
1. NJSP itself doesn't require root privileges (and should not be run as root!), but as a fastcgi host, it requires the HTTP server to be configured to actually _use_ it, and that would typically require root-like access. It's conceivable that Apache can be finagled into using a fastcgi server with .htaccess files, and it might be conceivable to use NJSP on a shared host through that, but that's a bit outside my area of expertise.

More critically, tho, PHP has, I believe, some kind of user management for shared servers, so that each user's pages run as their own account. NJSP has no such feature, and one is not planned in the short term.

2. NJSP pages are just Node scripts. You can import express, or nest.js, or any database engine, or anything you want, just as you could in any other Node script. The integration wouldn't be especially beautiful, since it's just at the level of one process communicating with other processes, but as long as all the other components can be communicated with via normal Node modules, they can all be used.

3. It is exactly as new as it looks. It has only been under development since February. However, unlike, e.g., PHP, there's really not much to _do_ here. I'm not writing a whole language, just some glue. The whole thing is barely 1,000 lines of code, but the right 1,000 lines of code in the right place can make all the difference. And, it's hard to hide too many bugs in 1,000 lines of code.

I use it to run https://ecastr.com/ ( https://github.com/Yahweasel/ennuicastr-server/ ), which is quite important to me, so it will continue to be developed to support that need. I do not know of any other users at the moment, but I consider it perfectly stable and usable, and would recommend it to anyone who's interested.
